### ISSUE TITLE
Not able to get data other than battery life and Device Name

### ISSUE THREAD

**Issue by ravishkumar24** [inFullMobile/inFullBand#3]
Hello mikchmie,

Thanks for the nice code with sample example.

I have integrated your code in my app , but it requires first pair Mi Band with Mi official app (Mi Fit) then only able to start Device data like steps , heartrate , cal , etc .

Is there any other way? so, app can pair with Mi Band without pairing with Mi Fit app.

Thanks again for your code and waiting for your guide and support

**Comment by mikchmie** [comment]
Hi. I'm glad you've found my code usefull.

I think that Mi Band might require pairing with official Mi Fit app by design. There's probably some configuration/activation going on when you pair it with Mi Fit. Notice that you even have to create a Xiaomi account, so just by that I would assume, that this process is mandatory.

Unfortunatelly I haven't used my code prior to pairing it with Mi Fit and Xiaomi account, so I don't have any tips for you regarding this matter.
