### ISSUE TITLE
Hi, i am using this to connect Mi band 3. It just says connecting but never connects

### ISSUE THREAD

**Issue by shezu** [inFullMobile/inFullBand#5]
Hi, i am using this to connect Mi band 3. It just says connecting but never connects, can you guide me how to connect Mi band 3 ?

**Comment by mikchmie** [comment]
Mi Band 2 and Mi Band 3 surely have different Bluetooth interfaces. This app is designed to work only with Mi Band 2. In order to use it with Mi Band 3, you would have to find the definition of its interface e.g. in [Gadgetbridge](https://github.com/Freeyourgadget/Gadgetbridge) repository and modify my app to use it.
